# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_match_start', models.BooleanField(default=True, verbose_name='Email when favorite team match starts')),
                ('email_match_result', models.BooleanField(default=True, verbose_name='Email final match scorecard summary')),
                ('email_breaking_news', models.BooleanField(default=False, verbose_name='Email breaking cricket news digest')),
                ('browser_live_score', models.BooleanField(default=True, verbose_name='Real-time browser notifications for live matches')),
                ('browser_wicket_alerts', models.BooleanField(default=True, verbose_name='Instant alert when a wicket falls')),
                ('sound_effects', models.BooleanField(default=True, verbose_name='Play audio sound on boundary (4/6) or wicket')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='SavedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Match',
                'verbose_name_plural': 'Saved Matches',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
