# Generated by Django 6.0.6 on 2026-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cricapi', 'CricAPI (cricapi.com)'), ('cricketdata', 'CricketData.org'), ('roanuz', 'Roanuz Cricket API'), ('mock', 'Internal Fallback / Mock Provider')], default='mock', max_length=30, verbose_name='active provider')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API key / Token')),
                ('api_endpoint', models.URLField(blank=True, default='', verbose_name='custom API endpoint URL')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enable external API sync')),
                ('refresh_interval_minutes', models.PositiveIntegerField(default=2, verbose_name='refresh interval (minutes)')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='last synchronization time')),
                ('last_sync_status', models.CharField(default='Initialized (Mock Provider Active)', max_length=100, verbose_name='last sync status')),
                ('last_error_message', models.TextField(blank=True, verbose_name='last error trace')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cricket API Setting',
                'verbose_name_plural': 'Cricket API Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CrickScore Live', max_length=100, verbose_name='website name')),
                ('site_tagline', models.CharField(default='Fastest Live Scores & Cricket Hub', max_length=200, verbose_name='site tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='site logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='site favicon')),
                ('primary_color', models.CharField(default='#047857', max_length=7, verbose_name='primary theme color')),
                ('secondary_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='secondary accent color')),
                ('banner_title', models.CharField(default='Real-Time Cricket Scores & Match Operations', max_length=200, verbose_name='homepage hero banner title')),
                ('banner_subtitle', models.CharField(default='Ball by ball coverage, tournaments, statistics and ICC rankings.', max_length=300, verbose_name='homepage hero banner subtitle')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='hero banner background image')),
                ('footer_text', models.TextField(default='© 2026 CrickScore Live. All rights reserved. The modern cricket scoring platform.', verbose_name='footer copyright text')),
                ('contact_email', models.EmailField(default='support@crickscore.local', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(default='+1 (800) 555-CRIC', max_length=30, verbose_name='contact phone')),
                ('address', models.CharField(default='Cricket Center Boulevard, Sports District', max_length=255, verbose_name='headquarters address')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', verbose_name='facebook page')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com', verbose_name='twitter / X profile')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', verbose_name='instagram profile')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', verbose_name='youtube channel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
