# Generated by Django 6.0.6 on 2026-09-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cricketapisetting_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CricketAPISetting',
        ),
    ]
