# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='series / tournament title')),
                ('short_name', models.CharField(max_length=50, verbose_name='short title')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug URL')),
                ('category', models.CharField(choices=[('international', 'International Bilateral / Tour'), ('icc_tournament', 'ICC Global Tournament'), ('ipl', 'IPL (Indian Premier League)'), ('psl', 'PSL (Pakistan Super League)'), ('bbl', 'BBL (Big Bash League)'), ('bpl', 'BPL (Bangladesh Premier League)'), ('cpl', 'CPL (Caribbean Premier League)'), ('sa20', 'SA20 League'), ('ilt20', 'ILT20 League'), ('hundred', 'The Hundred'), ('women', "Women's Cricket Tournament"), ('under19', 'Under-19 Cricket'), ('domestic', 'Domestic Championship')], default='international', max_length=30, verbose_name='competition category')),
                ('cricket_format', models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20', 'T20'), ('MIXED', 'Multi-Format Tour')], default='T20', max_length=15, verbose_name='format')),
                ('host_country', models.CharField(max_length=100, verbose_name='host nation / region')),
                ('start_date', models.DateField(verbose_name='tournament start date')),
                ('end_date', models.DateField(verbose_name='tournament end date')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='total scheduled matches')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='series/banners/', verbose_name='series hero banner')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured series')),
                ('is_active', models.BooleanField(default=True, verbose_name='ongoing or upcoming')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participating_teams', models.ManyToManyField(blank=True, related_name='tournaments', to='teams.team', verbose_name='participating teams')),
            ],
            options={
                'verbose_name': 'Series / Tournament',
                'verbose_name_plural': 'Series & Tournaments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PointsTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('tied_no_result', models.PositiveIntegerField(default=0)),
                ('net_run_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('points', models.PositiveIntegerField(default=0)),
                ('recent_form', models.CharField(default='-', help_text='e.g. W,W,L,W,L', max_length=20)),
                ('position', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_table', to='series.series')),
            ],
            options={
                'verbose_name': 'Points Table Entry',
                'verbose_name_plural': 'Points Table Standings',
                'ordering': ['position', '-points', '-net_run_rate'],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug'], name='series_seri_slug_bda3af_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['category'], name='series_seri_categor_049c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_active', 'is_featured'], name='series_seri_is_acti_b5ef7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointstableentry',
            unique_together={('series', 'team')},
        ),
    ]
