# Generated by Django 6.0.6 on 2026-09-20 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('user', 'Registered User'), ('guest', 'Guest')], default='user', max_length=20, verbose_name='user role')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar image')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio summary')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('favorite_team', models.CharField(blank=True, max_length=100, verbose_name='favorite cricket team')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('otp', models.CharField(blank=True, max_length=6, verbose_name='verification OTP')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP timestamp')),
                ('reset_token', models.CharField(blank=True, max_length=128, verbose_name='password reset token')),
                ('reset_token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='reset token timestamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'), models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'), models.Index(fields=['is_active', 'is_deleted'], name='accounts_cu_is_acti_0a92ff_idx')],
            },
        ),
    ]
