# Generated by Django 6.0.6 on 2026-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('scorer', 'Scorer'), ('user', 'Normal User')], default='user', max_length=20, verbose_name='user role'),
        ),
    ]
