# Generated by Django 6.0.6 on 2026-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_otp_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_hash',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_last_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token_created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='gender'),
        ),
    ]
