# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='full player name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug URL')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='nickname / popular name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/photos/', verbose_name='player portrait photo')),
                ('role', models.CharField(choices=[('batter', 'Top-order Batter'), ('wicketkeeper', 'Wicketkeeper Batter'), ('all_rounder', 'All-Rounder'), ('bowler', 'Bowler')], default='batter', max_length=30, verbose_name='primary playing role')),
                ('batting_style', models.CharField(choices=[('right_hand', 'Right Handed Bat'), ('left_hand', 'Left Handed Bat')], default='right_hand', max_length=30, verbose_name='batting style')),
                ('bowling_style', models.CharField(choices=[('right_fast', 'Right-arm Fast'), ('right_medium', 'Right-arm Medium'), ('right_off_spin', 'Right-arm Offbreak'), ('right_leg_spin', 'Right-arm Legbreak'), ('left_fast', 'Left-arm Fast'), ('left_medium', 'Left-arm Medium'), ('left_orthodox', 'Slow Left-arm Orthodox'), ('left_chinaman', 'Left-arm Unorthodox (Chinaman)'), ('none', 'None / Non-Bowler')], default='none', max_length=30, verbose_name='bowling style')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='jersey number')),
                ('born_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='birth place')),
                ('biography', models.TextField(blank=True, verbose_name='biography summary')),
                ('achievements', models.TextField(blank=True, verbose_name='career highlights & milestones')),
                ('records', models.TextField(blank=True, verbose_name='major records held')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured player')),
                ('is_active', models.BooleanField(default=True, verbose_name='currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_players', to='teams.team', verbose_name='national country team')),
                ('teams', models.ManyToManyField(blank=True, related_name='players', to='teams.team', verbose_name='teams & franchises')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BowlingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('TEST', 'Test Cricket'), ('ODI', 'One Day International (ODI)'), ('T20I', 'Twenty20 International (T20I)'), ('IPL', 'Indian Premier League (IPL)')], max_length=10)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('innings', models.PositiveIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('maidens', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('best_bowling', models.CharField(default='0/0', max_length=15)),
                ('bowling_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('economy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('four_wickets', models.PositiveIntegerField(default=0)),
                ('five_wickets', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Bowling Statistic',
                'verbose_name_plural': 'Bowling Statistics',
            },
        ),
        migrations.CreateModel(
            name='BattingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('TEST', 'Test Cricket'), ('ODI', 'One Day International (ODI)'), ('T20I', 'Twenty20 International (T20I)'), ('IPL', 'Indian Premier League (IPL)')], max_length=10)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('innings', models.PositiveIntegerField(default=0)),
                ('not_outs', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('highest_score', models.CharField(default='0', max_length=10)),
                ('batting_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Batting Statistic',
                'verbose_name_plural': 'Batting Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['slug'], name='players_pla_slug_839a41_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role'], name='players_pla_role_fe7c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_featured', 'is_active'], name='players_pla_is_feat_b3bccc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bowlingstat',
            unique_together={('player', 'format')},
        ),
        migrations.AlterUniqueTogether(
            name='battingstat',
            unique_together={('player', 'format')},
        ),
    ]
