# Generated by Django 6.0.6 on 2026-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_registration_status_player_country'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='player',
            new_name='players_pla_registr_5d59f1_idx',
            old_name='players_pla_reg_sta_idx',
        ),
    ]
