# Generated by Django 6.0.6 on 2026-09-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_contact_and_additional_fields'),
        ('players', '0003_rename_players_pla_reg_sta_idx_players_pla_registr_5d59f1_idx'),
    ]

    operations = [
    ]
