# Generated by Django 6.0.6 on 2026-09-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playerregistrationrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playerregistrationrequest',
            new_name='players_pla_status_f904a3_idx',
            old_name='players_req_status_idx',
        ),
        migrations.RenameIndex(
            model_name='playerregistrationrequest',
            new_name='players_pla_submitt_7496d7_idx',
            old_name='players_req_submitted_idx',
        ),
    ]
