# Generated by Django 6.0.6 on 2026-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_rename_players_req_status_idx_players_pla_status_f904a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='catches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses_as_captain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='run_outs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stumpings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins_as_captain',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
