# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('men', "Men's Cricket"), ('women', "Women's Cricket")], default='men', max_length=10)),
                ('cricket_format', models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20I', 'T20I')], default='TEST', max_length=10)),
                ('category', models.CharField(choices=[('teams', 'Team Rankings'), ('batters', 'Batters'), ('bowlers', 'Bowlers'), ('all_rounders', 'All-Rounders')], default='batters', max_length=20)),
                ('rank', models.PositiveIntegerField(verbose_name='rank position')),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='previous rank position')),
                ('name', models.CharField(max_length=120, verbose_name='display name')),
                ('country', models.CharField(max_length=100, verbose_name='country / nation')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='rating score')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='total points')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='teams.team')),
            ],
            options={
                'verbose_name': 'ICC Ranking Entry',
                'verbose_name_plural': 'ICC Rankings',
                'ordering': ['gender', 'cricket_format', 'category', 'rank'],
                'indexes': [models.Index(fields=['gender', 'cricket_format', 'category'], name='rankings_ra_gender_901998_idx'), models.Index(fields=['rank'], name='rankings_ra_rank_c32a0c_idx')],
            },
        ),
    ]
