# Generated by Django 6.0.6 on 2026-09-23 19:43

import apps.videos.storages
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180, verbose_name='video title')),
                ('video_file', models.FileField(storage=apps.videos.storages.video_storage, upload_to='videos/uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])], verbose_name='video file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded Video',
                'verbose_name_plural': 'Uploaded Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
