# Generated by Django 6.0.6 on 2026-09-20 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='team name')),
                ('short_name', models.CharField(max_length=10, verbose_name='short code')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug URL')),
                ('team_type', models.CharField(choices=[('international', 'International (Men)'), ('international_women', 'International (Women)'), ('ipl', 'IPL (Indian Premier League)'), ('domestic', 'Domestic First-Class'), ('league', 'T20 Global Leagues (BBL/PSL/CPL/SA20)'), ('under19', 'Under-19')], default='international', max_length=30, verbose_name='category')),
                ('country', models.CharField(max_length=100, verbose_name='country / region')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='team logo')),
                ('primary_color', models.CharField(default='#0f766e', max_length=7, verbose_name='primary color hex')),
                ('secondary_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='secondary color hex')),
                ('captain_name', models.CharField(blank=True, max_length=100, verbose_name='captain')),
                ('coach_name', models.CharField(blank=True, max_length=100, verbose_name='head coach')),
                ('home_venue', models.CharField(blank=True, max_length=150, verbose_name='home ground')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='established year')),
                ('history', models.TextField(blank=True, verbose_name='team history')),
                ('records', models.TextField(blank=True, verbose_name='notable records & trophies')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='total matches')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='matches won')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='matches lost')),
                ('total_ties_draws', models.PositiveIntegerField(default=0, verbose_name='ties / draws / no result')),
                ('trophies_count', models.PositiveIntegerField(default=0, verbose_name='trophies won')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured team')),
                ('is_active', models.BooleanField(default=True, verbose_name='active team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='teams_team_slug_1ce39f_idx'), models.Index(fields=['team_type'], name='teams_team_team_ty_40b61e_idx'), models.Index(fields=['is_featured', 'is_active'], name='teams_team_is_feat_3a9cbb_idx')],
            },
        ),
    ]
