# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='album title')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='slug URL')),
                ('category', models.CharField(choices=[('match', 'Match Action Photos'), ('player', 'Player Portraits & Moments'), ('team', 'Team Celebrations & Squads'), ('stadium', 'Venues & Stadiums'), ('ceremony', 'Awards & Ceremonies')], default='match', max_length=20, verbose_name='album category')),
                ('description', models.TextField(blank=True, verbose_name='album description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='photos/covers/%Y/%m/', verbose_name='album cover image')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_albums', to='matches.match')),
            ],
            options={
                'verbose_name': 'Photo Album',
                'verbose_name_plural': 'Photo Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/gallery/%Y/%m/', verbose_name='photo image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('photo_credit', models.CharField(default='CrickScore Media', max_length=100, verbose_name='credit / photographer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photoalbum')),
            ],
            options={
                'verbose_name': 'Photo Item',
                'verbose_name_plural': 'Photo Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
