# Generated by Django 6.0.6 on 2026-09-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('series', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='stadium name')),
                ('city', models.CharField(max_length=80, verbose_name='city')),
                ('country', models.CharField(max_length=80, verbose_name='country')),
                ('capacity', models.PositiveIntegerField(default=30000, verbose_name='seating capacity')),
                ('pitch_type', models.CharField(default='Batting friendly with early bounce', max_length=100, verbose_name='pitch characteristic')),
                ('avg_first_innings_score', models.PositiveIntegerField(default=175, verbose_name='average 1st innings score (T20/ODI)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
            ],
            options={
                'verbose_name': 'Cricket Stadium / Venue',
                'verbose_name_plural': 'Venues & Stadiums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.PositiveSmallIntegerField(default=1)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('overs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveSmallIntegerField(default=0)),
                ('wides', models.PositiveSmallIntegerField(default=0)),
                ('no_balls', models.PositiveSmallIntegerField(default=0)),
                ('byes', models.PositiveSmallIntegerField(default=0)),
                ('leg_byes', models.PositiveSmallIntegerField(default=0)),
                ('is_declared', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='teams.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match Innings',
                'verbose_name_plural': 'Match Innings',
                'ordering': ['innings_number'],
            },
        ),
        migrations.CreateModel(
            name='FallOfWicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wicket_number', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('overs', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_in_fow', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_of_wickets', to='matches.innings')),
            ],
            options={
                'ordering': ['wicket_number'],
            },
        ),
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('over_number', models.PositiveIntegerField()),
                ('ball_number', models.PositiveSmallIntegerField()),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0)),
                ('is_four', models.BooleanField(default=False)),
                ('is_six', models.BooleanField(default=False)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_description', models.CharField(blank=True, max_length=150)),
                ('is_wide', models.BooleanField(default=False)),
                ('is_no_ball', models.BooleanField(default=False)),
                ('is_bye', models.BooleanField(default=False)),
                ('is_leg_bye', models.BooleanField(default=False)),
                ('extra_runs', models.PositiveSmallIntegerField(default=0)),
                ('commentary', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='players.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='players.player')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balls_non_striker', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_deliveries', to='matches.innings')),
            ],
            options={
                'ordering': ['-over_number', '-ball_number', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. India vs Australia - 2nd ODI', max_length=200, verbose_name='match title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug URL')),
                ('match_number', models.CharField(default='1st Match', max_length=50, verbose_name='match stage')),
                ('match_type', models.CharField(choices=[('TEST', 'Test Match (5 Days)'), ('ODI', 'ODI (50 Overs)'), ('T20', 'T20 (20 Overs)'), ('T10', 'T10 (10 Overs)')], default='T20', max_length=15)),
                ('status', models.CharField(choices=[('upcoming', 'Scheduled / Upcoming'), ('live', 'LIVE in Progress'), ('break', 'Innings Break'), ('completed', 'Match Completed'), ('delayed', 'Delayed (Rain/Weather)'), ('abandoned', 'Abandoned / No Result')], db_index=True, default='upcoming', max_length=20)),
                ('current_innings_number', models.PositiveIntegerField(default=1)),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Elected to Bat First'), ('bowl', 'Elected to Bowl First')], max_length=10)),
                ('umpire_one', models.CharField(blank=True, default='Richard Kettleborough', max_length=80)),
                ('umpire_two', models.CharField(blank=True, default='Kumar Dharmasena', max_length=80)),
                ('tv_umpire', models.CharField(blank=True, default='Nitin Menon', max_length=80)),
                ('match_referee', models.CharField(blank=True, default='Javagal Srinath', max_length=80)),
                ('pitch_report', models.TextField(blank=True, default='Hard deck with consistent bounce. Expected to assist stroke-play initially, with spin coming into play under lights.')),
                ('weather_report', models.CharField(blank=True, default='Clear Skies, 28°C, Humidity 45%, Precipitation 0%', max_length=120)),
                ('result_text', models.CharField(blank=True, max_length=200, verbose_name='result summary')),
                ('start_datetime', models.DateTimeField(verbose_name='start date & time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='scheduled end time')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured match on hero section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('man_of_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potm_awards', to='players.player')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='series.series')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('team1_playing_xi', models.ManyToManyField(blank=True, related_name='team1_matches', to='players.player')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('team2_playing_xi', models.ManyToManyField(blank=True, related_name='team2_matches', to='players.player')),
                ('toss_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_won_matches', to='teams.team')),
                ('winning_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victories', to='teams.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_matches', to='matches.venue')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match'),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wicket_number', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('batter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_first', to='players.player')),
                ('batter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_second', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='matches.innings')),
            ],
            options={
                'ordering': ['wicket_number'],
            },
        ),
        migrations.CreateModel(
            name='BowlerMatchInnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveSmallIntegerField(default=0)),
                ('maidens', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('no_balls', models.PositiveIntegerField(default=0)),
                ('dots', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_bowling_records', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlers', to='matches.innings')),
            ],
            options={
                'ordering': ['-wickets', 'runs_conceded'],
                'unique_together': {('innings', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='innings',
            unique_together={('match', 'innings_number')},
        ),
        migrations.CreateModel(
            name='PlayerMatchInnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batting_position', models.PositiveSmallIntegerField(default=1)),
                ('dismissal', models.CharField(choices=[('not_out', 'Not Out'), ('bowled', 'b'), ('caught', 'c'), ('lbw', 'lbw b'), ('run_out', 'run out'), ('stumped', 'st'), ('hit_wicket', 'hit wicket'), ('retired_hurt', 'retired hurt')], default='not_out', max_length=20)),
                ('dismissal_text', models.CharField(blank=True, default='not out', max_length=150)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('dots', models.PositiveIntegerField(default=0)),
                ('dismissal_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals_bowled', to='players.player')),
                ('dismissal_fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals_fielded', to='players.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batters', to='matches.innings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_batting_records', to='players.player')),
            ],
            options={
                'ordering': ['batting_position'],
                'unique_together': {('innings', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', '-start_datetime'], name='matches_mat_status_dffc25_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['slug'], name='matches_mat_slug_942699_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_featured'], name='matches_mat_is_feat_875083_idx'),
        ),
    ]
