# Generated by Django 6.0.6 on 2026-09-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('overs_per_innings', models.PositiveSmallIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='extra_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='is_free_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='review_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innings',
            name='break_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='innings',
            name='free_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innings',
            name='powerplay_overs',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='innings',
            name='target_runs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ball_type',
            field=models.CharField(default='Leather', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='overs_limit',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='match',
            name='pitch_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='scorer',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_team1_matches', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captained_team1_matches', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_team2_matches', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captained_team2_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='batter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_faced', to='players.player'),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_bowled', to='players.player'),
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grounds', to='matches.venue')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='ground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.ground'),
        ),
        migrations.AddField(
            model_name='match',
            name='officials',
            field=models.ManyToManyField(blank=True, related_name='matches', to='matches.official'),
        ),
        migrations.AddField(
            model_name='match',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='matches', to='matches.sponsor'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.tournament'),
        ),
    ]
