# Generated by Django 6.0.6 on 2026-09-20 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_official_sponsor_tournament_ballbyball_extra_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='assigned_scorers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'scorer'}, related_name='assigned_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
