# Generated by Django 6.0.6 on 2026-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_assigned_scorers'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=80, verbose_name='state'),
        ),
    ]
