# Generated by Django 6.0.6 on 2026-09-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_ground_created_at_ground_updated_at_and_more'),
        ('players', '0006_rename_players_req_status_idx_players_pla_status_f904a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actual_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual start date & time'),
        ),
        migrations.AddField(
            model_name='match',
            name='opening_batter_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_batter_one_matches', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='opening_batter_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_batter_two_matches', to='players.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='opening_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_bowler_matches', to='players.player'),
        ),
    ]
