# Generated by Django 6.0.6 on 2026-09-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_actual_start_datetime_match_opening_batter_one_and_more'),
        ('players', '0006_rename_players_req_status_idx_players_pla_status_f904a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballbyball',
            name='dismissal_position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='dismissed_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissal_deliveries', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_innings_current', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striking_innings', to='players.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striking_innings', to='players.player'),
        ),
    ]
