# Generated by Django 6.0.6 on 2026-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_ballbyball_dismissal_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stats_processed',
            field=models.BooleanField(default=False),
        ),
    ]
